/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdmin;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;import Business.UserAccount.UserAccountDirectory;import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shshyam
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccountDirectory userAccountList;
   
    public ManageCustomerJPanel(JPanel parentContainerPanel,EcoSystem ecosystem) {
        initComponents();
        initListners();
        this.userProcessContainer=parentContainerPanel;
        this.ecosystem=ecosystem;
         populateTable();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnCreateCustomer = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPhnNum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(182, 216, 242));
        setPreferredSize(new java.awt.Dimension(920, 708));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomer.setFont(new java.awt.Font("Optima", 0, 12)); // NOI18N
        tblCustomer.setForeground(new java.awt.Color(87, 132, 186));
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);
        if (tblCustomer.getColumnModel().getColumnCount() > 0) {
            tblCustomer.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 643, 165));

        jLabel1.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create/Update Customer Profiles");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 36, 643, -1));

        jLabel2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Username              :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 470, -1));

        jLabel3.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Password               :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 470, -1));

        jLabel4.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Customer Name    :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 470, -1));

        jLabel5.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Customer Address :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 470, -1));

        btnCreateCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateCustomer.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnCreateCustomer.setForeground(new java.awt.Color(87, 132, 186));
        btnCreateCustomer.setText("Create");
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });
        add(btnCreateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 180, 50));

        btnModify.setBackground(new java.awt.Color(255, 255, 255));
        btnModify.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnModify.setForeground(new java.awt.Color(87, 132, 186));
        btnModify.setText("Update");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 180, 50));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(87, 132, 186));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 180, 50));

        jLabel6.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Contact Number     :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));
        add(txtPhnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 470, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        // TODO add your handling code here:
        
          if( txtUserName.getText().isEmpty()||txtPassword.getText().isEmpty()|| txtName.getText().isEmpty() || txtAddress.getText().isEmpty() || txtPhnNum.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
          Pattern TelNumpattern = Pattern.compile("^\\d{10}$");
        Matcher TelNummatcher = TelNumpattern.matcher(txtPhnNum.getText());
        if (TelNummatcher.matches()==false)
        {
                JOptionPane.showMessageDialog(this, "Phone Number format Invalid!"); 
                return;
        }
        
         if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtUserName.getText())){
            Customer customer = new Customer(txtUserName.getText(), txtPassword.getText(), txtName.getText(), txtAddress.getText(), txtPhnNum.getText());
            ecosystem.getUserAccountDirectory().addUserAccount(customer);
            ecosystem.getCustomerDirectory().addCustomer(customer);
            populateTable();
            txtUserName.setText("");
            txtPassword.setText("");
            txtName.setText("");
            txtAddress.setText("");
            txtPhnNum.setText("");
         }else{
            JOptionPane.showMessageDialog(null, "Username " + txtUserName.getText() + " already exists !!!, Please try a new one");
         }
    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
            

        int selectedRow = tblCustomer.getSelectedRow();
        if (selectedRow >= 0) {
         
            Customer customer = (Customer) tblCustomer.getValueAt(selectedRow, 0);
            if( txtUserName.getText().isEmpty()||txtPassword.getText().isEmpty()|| txtName.getText().isEmpty() || txtAddress.getText().isEmpty() || txtPhnNum.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
          Pattern TelNumpattern = Pattern.compile("^\\d{10}$");
        Matcher TelNummatcher = TelNumpattern.matcher(txtPhnNum.getText());
        if (TelNummatcher.matches()==false)
        {
                JOptionPane.showMessageDialog(this, "Phone Number format Invalid!"); 
                return;
        }
        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtUserName.getText()) || (customer.getUsername().equals(txtUserName.getText()))){
          
            customer.setUsername(txtUserName.getText());
            customer.setPassword(txtPassword.getText());
            customer.setName(txtName.getText());
            customer.setPhone(txtPhnNum.getText());
            customer.setAddress(txtAddress.getText());
            populateTable();
            txtUserName.setText("");
            txtPassword.setText("");
            txtName.setText("");
            txtPhnNum.setText("");
            txtAddress.setText("");
            }else{
            JOptionPane.showMessageDialog(null, "Username " + txtUserName.getText() + " already exists !!!, Please try a new one");
         }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         int selectedRow = tblCustomer.getSelectedRow();

        if (selectedRow >= 0) {
            Customer customer = (Customer) tblCustomer.getValueAt(selectedRow, 0);
           CustomerDirectory customerDirectory = ecosystem.getCustomerDirectory();
            customerDirectory.removeCustomer(customer);
            JOptionPane.showMessageDialog(null, "Customer   "  + txtUserName.getText() + " deleted");
            populateTable();
            txtName.setText("");
            txtPhnNum.setText("");
            txtUserName.setText("");
            txtPassword.setText("");
            txtAddress.setText("");
           
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
     private void populateTable() {
        CustomerDirectory customerDirectory = ecosystem.getCustomerDirectory();
        DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();

        model.setRowCount(0);
        for (Customer customer : customerDirectory.getCustomerList()) {
                    Object[] row = new Object[5];
                    row[0] = customer;
                    row[1] = customer.getUsername();
                    row[2] = customer.getPassword();

                    model.addRow(row);
                
            }
        
    }
       private void initListners() {
       tblCustomer.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
           int selectedRow = tblCustomer.getSelectedRow();
             if (selectedRow >= 0) {
                  Customer  customer  = (Customer) tblCustomer.getValueAt(selectedRow, 0);
                 if(customer!=null){
                     display(customer);
                 }
             }
        }
    });
    }
     

    private void display(Customer customer) {
       
        txtUserName.setText(customer.getUsername());
        txtPassword.setText(customer.getPassword());
        txtName.setText(customer.getName());
        txtPhnNum.setText(customer.getPhone());
        txtAddress.setText(customer.getAddress());
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhnNum;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
