/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdmin;

import Business.EcoSystem;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        //this.set
        
        initComponents();
   
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        manageCustomer();
    }
    
//    public void populateTree(){
//        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
//       // Add the code for draw your system structure shown by JTree
//       
//        model.reload();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnManageCust = new javax.swing.JButton();
        btnManageDel = new javax.swing.JButton();
        btnManageRest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rightSystemAdminPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(31, 50, 97));
        setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(240, 178, 62));

        jPanel1.setBackground(new java.awt.Color(87, 132, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageCust.setBackground(new java.awt.Color(255, 255, 255));
        btnManageCust.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnManageCust.setForeground(new java.awt.Color(87, 132, 186));
        btnManageCust.setText("<html><center>Create/Update</br>Customer Profiles</center></html>");
        btnManageCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 268, 67));

        btnManageDel.setBackground(new java.awt.Color(255, 255, 255));
        btnManageDel.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnManageDel.setForeground(new java.awt.Color(87, 132, 186));
        btnManageDel.setText("<html><center>Create/Update</br>Delivery Partners</center></html>");
        btnManageDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 268, 67));

        btnManageRest.setBackground(new java.awt.Color(255, 255, 255));
        btnManageRest.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnManageRest.setForeground(new java.awt.Color(87, 132, 186));
        btnManageRest.setText("<html><center>Create/Update</br>Restaurant Partners</center></html>");
        btnManageRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRestActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 268, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Webp.net-resizeimage.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 150));

        rightSystemAdminPanel.setPreferredSize(new java.awt.Dimension(940, 808));
        rightSystemAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        add(systemAdminPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDelActionPerformed
        // TODO add your handling code here:
        manageDeliveryPartner();
    }//GEN-LAST:event_btnManageDelActionPerformed

    private void btnManageCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustActionPerformed
        // TODO add your handling code here:
        manageCustomer();
    }//GEN-LAST:event_btnManageCustActionPerformed

    private void btnManageRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRestActionPerformed
        // TODO add your handling code here:
        manageRestaurant();
    }//GEN-LAST:event_btnManageRestActionPerformed

    private void manageCustomer() {
        // TODO add your handling code here:
        
        userinterface.SystemAdmin.ManageCustomerJPanel manageCustomer = new userinterface.SystemAdmin.ManageCustomerJPanel(rightSystemAdminPanel, ecosystem);
        rightSystemAdminPanel.add("ManageCustomerJPanel",manageCustomer);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageRestaurant() {
        // TODO add your handling code here:
        
        userinterface.SystemAdmin.ManageRestaurantJPanel manageRestaurant = new userinterface.SystemAdmin.ManageRestaurantJPanel(rightSystemAdminPanel, ecosystem);
        rightSystemAdminPanel.add("ManageRestaurantJPanel",manageRestaurant);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageDeliveryPartner() {
        // TODO add your handling code here:
        
        userinterface.SystemAdmin.ManageDeliveryPartnerJPanel manageDeliveryMan = new userinterface.SystemAdmin.ManageDeliveryPartnerJPanel(rightSystemAdminPanel, ecosystem);
        rightSystemAdminPanel.add("ManageDeliveryManJPanel",manageDeliveryMan);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCust;
    private javax.swing.JButton btnManageDel;
    private javax.swing.JButton btnManageRest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel rightSystemAdminPanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
